### PR TITLE
 add docs ERD

### PR DESCRIPTION
**Pull request by atenaiis**
Team.

This is my first code review for this project, I added docs file and the ERD in it.

cheers.

Atenais Campos

### CODE REVIEW

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:wrench::hammer::full_moon:
**Hi Atanails!
Great job on this milestone:clap::clap:.**

**Major highlights**
- The PR is very descriptive. Keep up the good work

However, we just need to make a few changes to the ERD to get it approved:muscle:.

**To improve**
- [x] Friendship table
- Replace `field` with `status`
- Replace `accepted` with `friend_id` and should have a `FK`
- Connect another link from this table (another association) just like the first one to the `User` table. 

- [x] User table
- Remove `password` and `email`. They are not needed.

- [x] All tables
- Replace `id` with `ID` for all the PK's. This is to allow one to easily differentiate a primary key from a foreign-key

Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Comment by atenaiis** [comment]
thanks for the comments!!

I worked on requested changes.

cheers :)

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Atenais Campos García** 
Good job with the improvements for this project :muscle:  :muscle:
You addressed the changes requested by the previous TSE :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] In the Friendship model, friend_id should also be a foreign key. 
- [ ] Remove word "text" from the cardinality between User and Friendship.
- [ ] In the Friendship model, remove "Key" from the status field.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by atenaiis** [comment]
Thanks for that quick review.
I made the changes!

cheers!

**Review by rukundoeric — APPROVED** [review]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - [x] The project follows Git flow. 💯
  - [x] All feedback are implemented 💯


- ### To Improve
  - n/a

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

**Pull request closed without merging**
